springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
server:
  port: 9080

#   mybatis_config
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

  #datasource
spring:
  application:
    name: test-service
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    master :
      driverClassName: com.mysql.jdbc.Driver
      .jdbc-url: jdbc:mysql://192.168.229.130:3306/test_slave
      username: root
      password: root
      initSize: 5
      maxActive: 20
      minIdle:  5
      maxWait: 5000
      testOnReturn: true
    slave1 :
      driverClassName: com.mysql.jdbc.Driver
      .jdbc-url: jdbc:mysql://192.168.229.131:3306/test_slave
      username: root
      password: root
      initSize: 5
      maxActive: 20
      minIdle:  5
      maxWait: 5000
      testOnReturn: true

elasticsearch:
  user:
  password:
  host: 192.168.159.1:9200
    #============== kafka ===================
    # 指定kafka 代理地址，可以多个
#  kafka:
#    bootstrap-servers: 192.168.229.130:9092
#    producer:
#      retries: 0
#      batch-size: 16384
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: test1-group
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 100
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    listener:
#      missing-topics-fatal: false
    #=============== provider  =======================

#    spring.kafka.producer.retries=0
#    # 每次批量发送消息的数量
#    spring.kafka.producer.batch-size=16384
#    spring.kafka.producer.buffer-memory=33554432
#
#    # 指定消息key和消息体的编解码方式
#    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#    spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#
#    #=============== consumer  =======================
#    # 指定默认消费者group id
#    spring.kafka.consumer.group-id=test-hello-group
#
#    spring.kafka.consumer.auto-offset-reset=earliest
#    spring.kafka.consumer.enable-auto-commit=true
#    spring.kafka.consumer.auto-commit-interval=100
#
#    # 指定消息key和消息体的编解码方式
#    spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#    spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
